### PR TITLE
Update juju-openstack-controller-example for juju 2.7

### PR DESCRIPTION
**Pull request by ryan-beisner**

### CODE REVIEW

**Comment by ryan-beisner** [comment]
FYI, here it is, working:

```
jenkins@juju-001b34-osci-5:~/temp/charm-test-infra$ juju --version
2.7-beta1-xenial-amd64
jenkins@juju-001b34-osci-5:~/temp/charm-test-infra$ ./juju-destroy-controller-and-models-example.sh -y
+ : serverstack
+ : auto-osci-sv00
+ grep 'auto-osci-sv00.*superuser'
+ juju controllers
auto-osci-sv00*  auto-osci-sv00  admin  superuser  serverstack/serverstack       3      1  none  2.7-beta1  
+ juju switch auto-osci-sv00:controller
auto-osci-sv00:admin/auto-osci-sv00 -> auto-osci-sv00:admin/controller
+ timeout 1200 juju destroy-controller --destroy-storage --destroy-all-models -y auto-osci-sv00
Destroying controller
Waiting for hosted model resources to be reclaimed
Waiting on 2 models
Waiting on 2 models
Waiting on 2 models
Waiting on 1 model
Waiting on 1 model
All hosted models reclaimed, cleaning up controller machines
jenkins@juju-001b34-osci-5:~/temp/charm-test-infra$ 
```
```
jenkins@juju-001b34-osci-5:~/temp/charm-test-infra$ ./juju-openstack-controller-example.sh
+ : serverstack
+ : auto-osci-sv00
+ : auto-osci-sv00
+ : 4c2bea54-8c9e-45d3-be24-944de3021d14
+ : virt-type=kvm cores=4 mem=8G
+ : virt-type=kvm
+ : /tmp
+ juju --version
2.7-beta1-xenial-amd64
+ grep serverstack-keystone juju-configs/clouds.yaml
+ :
+ juju show-cloud serverstack
+ juju update-cloud serverstack -f juju-configs/clouds.yaml --client
+ juju switch auto-osci-sv00
+ juju bootstrap --bootstrap-constraints 'virt-type=kvm cores=4 mem=8G' --constraints virt-type=kvm --auto-upgrade=false --model-default=juju-configs/model-default-serverstack.yaml --config=juju-configs/controller-default.yaml --config network=4c2bea54-8c9e-45d3-be24-944de3021d14 serverstack/serverstack auto-osci-sv00
Creating Juju controller "auto-osci-sv00" on serverstack/serverstack
Looking for packaged Juju agent version 2.7-beta1 for amd64
No packaged binary found, preparing local Juju agent binary
Launching controller instance(s) on serverstack/serverstack...
 - c701d1a1-c149-4ac3-a7f7-379ffbbaab34 (arch=amd64 mem=8G cores=4), wait 10 seconds before retry, attempt 1
Installing Juju agent on bootstrap instance
Fetching Juju GUI 2.15.0
Waiting for address
Attempting to connect to 172.17.100.12:22
Connected to 172.17.100.12
Running machine configuration script...
Bootstrap agent now started
Contacting Juju controller at 172.17.100.12 to verify accessibility...

Bootstrap complete, controller "auto-osci-sv00" now is available
Controller machines are in the "controller" model
Initial model "default" added

real    3m12.044s
user    0m17.600s
sys     0m4.560s
+ juju model-defaults network=4c2bea54-8c9e-45d3-be24-944de3021d14
+ juju show-model auto-osci-sv00:auto-osci-sv00
+ juju add-model auto-osci-sv00 serverstack --config=juju-configs/model-default-serverstack.yaml --config network=4c2bea54-8c9e-45d3-be24-944de3021d14
Added 'auto-osci-sv00' model on serverstack/serverstack with credential 'osci' for user 'admin'
+ juju models --format json -o /tmp/juju-models-before-constraints.json.txt
+ juju set-model-constraints -m auto-osci-sv00 virt-type=kvm
+ juju controllers --refresh
Controller       Model           User   Access     Cloud/Region             Models  Nodes    HA  Version
auto-osci-sv00*  auto-osci-sv00  admin  superuser  serverstack/serverstack       3      1  none  2.7-beta1

+ juju machines -m controller
Machine  State    DNS            Inst id                               Series  AZ    Message
0        started  172.17.100.12  c701d1a1-c149-4ac3-a7f7-379ffbbaab34  bionic  nova

+ juju models --all
Controller: auto-osci-sv00

Model            Cloud/Region             Type       Status     Machines  Cores  Access  Last connection
auto-osci-sv00*  serverstack/serverstack  openstack  available         0      -  admin   just now
controller       serverstack/serverstack  openstack  available         1      4  admin   just now
default          serverstack/serverstack  openstack  available         0      -  admin   4 seconds ago

+ juju status --color
Model           Controller      Cloud/Region             Version    SLA          Timestamp
auto-osci-sv00  auto-osci-sv00  serverstack/serverstack  2.7-beta1  unsupported  18:32:34Z

Model "admin/auto-osci-sv00" is empty.
jenkins@juju-001b34-osci-5:~/temp/charm-test-infra$
```
Just to confirm that it is idempotent:
```
jenkins@juju-001b34-osci-5:~/temp/charm-test-infra$ ./juju-openstack-controller-example.sh 
+ : serverstack
+ : auto-osci-sv00
+ : auto-osci-sv00
+ : 4c2bea54-8c9e-45d3-be24-944de3021d14
+ : virt-type=kvm cores=4 mem=8G
+ : virt-type=kvm
+ : /tmp
+ juju --version
2.7-beta1-xenial-amd64
+ grep serverstack-keystone juju-configs/clouds.yaml
+ :
+ juju show-cloud serverstack
+ juju update-cloud serverstack -f juju-configs/clouds.yaml --client
+ juju switch auto-osci-sv00
+ timeout 15 juju show-controller auto-osci-sv00
+ juju model-defaults network=4c2bea54-8c9e-45d3-be24-944de3021d14
+ juju show-model auto-osci-sv00:auto-osci-sv00
+ juju models --format json -o /tmp/juju-models-before-constraints.json.txt
+ juju set-model-constraints -m auto-osci-sv00 virt-type=kvm
+ juju controllers --refresh
Controller       Model           User   Access     Cloud/Region             Models  Nodes    HA  Version
auto-osci-sv00*  auto-osci-sv00  admin  superuser  serverstack/serverstack       3      1  none  2.7-beta1  

+ juju machines -m controller
Machine  State    DNS            Inst id                               Series  AZ    Message
0        started  172.17.100.12  c701d1a1-c149-4ac3-a7f7-379ffbbaab34  bionic  nova  ACTIVE

+ juju models --all
Controller: auto-osci-sv00

Model            Cloud/Region             Type       Status     Machines  Cores  Access  Last connection
auto-osci-sv00*  serverstack/serverstack  openstack  available         0      -  admin   just now
controller       serverstack/serverstack  openstack  available         1      4  admin   just now
default          serverstack/serverstack  openstack  available         0      -  admin   2 minutes ago

+ juju status --color
Model           Controller      Cloud/Region             Version    SLA          Timestamp
auto-osci-sv00  auto-osci-sv00  serverstack/serverstack  2.7-beta1  unsupported  18:35:06Z

Model "admin/auto-osci-sv00" is empty.
jenkins@juju-001b34-osci-5:~/temp/charm-test-infra$ 
```

**Comment by ryan-beisner** [comment]
FYI, just a note:  In the future, --local will be removed, and we should use --client instead.  However, that would *require* all users to use 2.7 as a minimum, and I'm not sure that's best at this moment (with 2.7 only available in edge).

```
jenkins@juju-001b34-osci-6:~/temp/charm-test-infra$ ./juju-openstack-controller-example.sh 
+ : serverstack
+ : auto-osci-sv01
+ : auto-osci-sv01
+ : 3963d364-f2fb-4d29-a3a6-ffeed1f03450
+ : virt-type=kvm cores=4 mem=8G
+ : virt-type=kvm
+ : /tmp
+ juju --version
2.6.9-xenial-amd64
+ grep serverstack-keystone juju-configs/clouds.yaml
    endpoint: http://serverstack-keystone:5000/v3
        endpoint: http://serverstack-keystone:5000/v3
+ sed -e s#http://serverstack-keystone:5000/v3#http://10.245.161.156:5000/v3#g -i juju-configs/clouds.yaml
+ juju show-cloud serverstack
+ juju update-cloud serverstack -f juju-configs/clouds.yaml --client
+ juju add-cloud serverstack -f juju-configs/clouds.yaml --client
ERROR option provided but not defined: --client
```

**Comment by ryan-beisner** [comment]
Works with 2.6 too:

```
jenkins@juju-001b34-osci-6:~/temp/charm-test-infra$ ./juju-openstack-controller-example.sh
+ : serverstack
+ : auto-osci-sv01
+ : auto-osci-sv01
+ : 3963d364-f2fb-4d29-a3a6-ffeed1f03450
+ : virt-type=kvm cores=4 mem=8G
+ : virt-type=kvm
+ : /tmp
+ juju --version
2.6.9-xenial-amd64
+ grep serverstack-keystone juju-configs/clouds.yaml
+ :
+ juju show-cloud serverstack
+ juju update-cloud serverstack -f juju-configs/clouds.yaml --local
+ juju switch auto-osci-sv01
+ juju bootstrap --bootstrap-constraints 'virt-type=kvm cores=4 mem=8G' --constraints virt-type=kvm --auto-upgrade=false --model-default=juju-configs/model-default-serverstack.yaml --config=juju-configs/controller-default.yaml --config network=3963d364-f2fb-4d29-a3a6-ffeed1f03450 serverstack/serverstack auto-osci-sv01
Creating Juju controller "auto-osci-sv01" on serverstack/serverstack
Looking for packaged Juju agent version 2.6.9 for amd64
Launching controller instance(s) on serverstack/serverstack...
 - 07b8230c-eef6-4855-adee-fd449fb83d67 (arch=amd64 mem=8G cores=4), wait 10 seconds before retry, attempt 2
Installing Juju agent on bootstrap instance
Fetching Juju GUI 2.15.0
Waiting for address
Attempting to connect to 172.17.101.3:22
Connected to 172.17.101.3
Running machine configuration script...
Bootstrap agent now started
Contacting Juju controller at 172.17.101.3 to verify accessibility...

Bootstrap complete, controller "auto-osci-sv01" now is available
Controller machines are in the "controller" model
Initial model "default" added

real    2m8.706s
user    0m2.392s
sys     0m0.196s
+ juju model-defaults network=3963d364-f2fb-4d29-a3a6-ffeed1f03450
+ juju show-model auto-osci-sv01:auto-osci-sv01
+ juju add-model auto-osci-sv01 serverstack --config=juju-configs/model-default-serverstack.yaml --config network=3963d364-f2fb-4d29-a3a6-ffeed1f03450
Added 'auto-osci-sv01' model on serverstack/serverstack with credential 'osci' for user 'admin'
+ juju models --format json -o /tmp/juju-models-before-constraints.json.txt
+ juju set-model-constraints -m auto-osci-sv01 virt-type=kvm
+ juju controllers --refresh
Controller       Model           User   Access     Cloud/Region             Models  Nodes    HA  Version
auto-osci-sv01*  auto-osci-sv01  admin  superuser  serverstack/serverstack       3      1  none  2.6.9

+ juju machines -m controller
Machine  State    DNS           Inst id                               Series  AZ    Message
0        pending  172.17.101.3  07b8230c-eef6-4855-adee-fd449fb83d67  bionic  nova

+ juju models --all
Controller: auto-osci-sv01

Model            Cloud/Region             Type       Status     Machines  Cores  Access  Last connection
auto-osci-sv01*  serverstack/serverstack  openstack  available         0      -  admin   just now
controller       serverstack/serverstack  openstack  available         1      4  admin   just now
default          serverstack/serverstack  openstack  available         0      -  admin   3 seconds ago

+ juju status --color
Model           Controller      Cloud/Region             Version  SLA          Timestamp
auto-osci-sv01  auto-osci-sv01  serverstack/serverstack  2.6.9    unsupported  18:46:18Z

Model "admin/auto-osci-sv01" is empty.
jenkins@juju-001b34-osci-6:~/temp/charm-test-infra$
```

**Comment by ryan-beisner** [comment]
Still ok @ 2.7 with --local instead of --client:

```
jenkins@juju-001b34-osci-5:~/temp/charm-test-infra$ ./juju-openstack-controller-example.sh 
+ : serverstack
+ : auto-osci-sv00
+ : auto-osci-sv00
+ : 4c2bea54-8c9e-45d3-be24-944de3021d14
+ : virt-type=kvm cores=4 mem=8G
+ : virt-type=kvm
+ : /tmp
+ juju --version
2.7-beta1-xenial-amd64
+ grep serverstack-keystone juju-configs/clouds.yaml
+ :
+ juju show-cloud serverstack
+ juju update-cloud serverstack -f juju-configs/clouds.yaml --local
+ juju switch auto-osci-sv00
+ timeout 15 juju show-controller auto-osci-sv00
+ juju model-defaults network=4c2bea54-8c9e-45d3-be24-944de3021d14
+ juju show-model auto-osci-sv00:auto-osci-sv00
+ juju models --format json -o /tmp/juju-models-before-constraints.json.txt
+ juju set-model-constraints -m auto-osci-sv00 virt-type=kvm
+ juju controllers --refresh
Controller       Model           User   Access     Cloud/Region             Models  Nodes    HA  Version
auto-osci-sv00*  auto-osci-sv00  admin  superuser  serverstack/serverstack       3      1  none  2.7-beta1  

+ juju machines -m controller
Machine  State    DNS            Inst id                               Series  AZ    Message
0        started  172.17.100.12  c701d1a1-c149-4ac3-a7f7-379ffbbaab34  bionic  nova  ACTIVE

+ juju models --all
Controller: auto-osci-sv00

Model            Cloud/Region             Type       Status     Machines  Cores  Access  Last connection
auto-osci-sv00*  serverstack/serverstack  openstack  available         0      -  admin   just now
controller       serverstack/serverstack  openstack  available         1      4  admin   just now
default          serverstack/serverstack  openstack  available         0      -  admin   14 minutes ago

+ juju status --color
Model           Controller      Cloud/Region             Version    SLA          Timestamp
auto-osci-sv00  auto-osci-sv00  serverstack/serverstack  2.7-beta1  unsupported  18:47:07Z

Model "admin/auto-osci-sv00" is empty.
```

**Review by thedac — APPROVED** [review]
LGTM

**Pull request merged**
